### PR TITLE
Refactor : updated the tests so that LIC,PUM,FUV and DECIDE tests are…

### LINKED ISSUE #46: Refactor tests. LIC tests should be in a seperate file than the DECIDE tests

### PR DESCRIPTION
**Pull request by raeef96**
… separated and are in different folders #46

### CODE REVIEW

**Review by Gustaf-Larsson — CHANGES_REQUESTED** [review]
All test classes should be in the same folder but the classes should be named accordingly to what function they test.

**Review by andrefred — CHANGES_REQUESTED** [review]
Class names should vary, be informative of what tests they include, and all be placed in the same test folder.

**Review by Gustaf-Larsson — APPROVED** [review]
looks good now!

**Review by andrefred — APPROVED** [review]
This test structure looks good!

**Pull request merged**
